### ISSUE TITLE
Add - Recurring Weekday Call Allotments.

### ISSUE THREAD

**Issue by samuelGrahame** [IntelogyGroup/BusinessManagerIssues#327] opened 2018-08-22 03:15 UTC
Add 7 Check Box's
Add 7 Reason Text Fields to Employee
Add 7 Edit Box to Set Max Call for that day.

If there is a unavailable day it is high priority over these days. aka public holiday.

**Comment by bLeenstra** [comment] 2018-08-29 03:29
Likely duplicate of #101

**Comment by bLeenstra** [comment] 2018-08-29 03:30
closed #101 as this thread contains more information regardless

**Closed as completed** 2020-11-30 00:54 UTC
Labels: Enhancement
