### ISSUE TITLE
parts received from an order not showing in transferred

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#250] opened 2018-07-02 05:22 UTC

**Comment by samuelGrahame** [comment] 2018-07-02 23:13
This is not an issue, There are two option's part orders get automatically transferred and handled from the order screen. or they go through picking slip's. This is by design.

**Comment by sydapp992** [comment] 2018-07-03 02:14
Yes please, this will show all the parts that received in and also transferred from warehouse.

- thanks for removing,

**Comment by samuelGrahame** [comment] 2018-07-06 05:55
This has been completed, will be in the next version

**Closed by samuelGrahame** 2018-07-06 05:55 UTC
