### ISSUE TITLE
Column layout not saving

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#185] opened 2018-06-12 05:46 UTC
Column layout not saving also added column not staying on soon as refreshed goes away.

**Comment by bLeenstra** [comment] 2018-06-12 06:17
To clarify - This is in the picking slip screen

**Comment by sydapp992** [comment] 2018-06-12 23:07
it's all over none of the column layouts are saving. when i refresh and close window and open again same thing happens.

**Comment by bLeenstra** [comment] 2018-06-19 01:10
Couldnt Reproduce locally, may be a combination of items making this issue occur

**Comment by samuelGrahame** [comment] 2018-06-26 02:56
Closing this because old, i believe this was to do with picking slips.

**Closed by samuelGrahame** 2018-06-26 02:56 UTC
Labels: Can't Reproduce
