### ISSUE TITLE
Changing Tech when Run locked (CRASH)

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#268] opened 2018-07-11 07:28 UTC
298383 was on our tech (Martin), we tried changing to (Chris) or anyone, bm just froze each time. 
I tried unticking service call required it advised me that the job was locked. so i went to unlock the day and then re-allocate tech. works fine. please rectify the issue causing freeze and crash.

**Comment by bLeenstra** [comment] 2018-07-11 23:48
Was intended to be fixed in v378 - issue still occurs depending on call allotment
Fixed again in v379

**Closed by bLeenstra** 2018-07-11 23:48 UTC
Labels: Exception
