### ISSUE TITLE
Error - Message when adding parts

### ISSUE THREAD

**Issue by thevideofactory** [IntelogyGroup/BusinessManagerIssues#146] opened 2018-06-01 01:29 UTC
Object reference not set to an instance of an object.   at Intelogy___Business_Manager.v8_DATA_Repair.SetFocusOnColumnAndSetValue(GridColumn col, Object value)   at Intelogy___Business_Manager.v8_DATA_Repair.SimpleButton13_Click_1(Object sender, EventArgs e)   at System.Windows.Forms.Control.OnClick(EventArgs e)   at DevExpress.XtraEditors.BaseButton.OnClick(EventArgs e)   at DevExpress.XtraEditors.BaseButton.OnMouseUp(MouseEventArgs e)   at System.Windows.Forms.Control.WmMouseUp(Message

**Comment by bLeenstra** [comment] 2018-06-01 01:34
While we where not able to reproduce this issue we believe we have fixed the cause of the issue in v363
I will leave the issue open for a week to see if there are any further occurances

**Comment by bLeenstra** [comment] 2018-06-01 01:35
Extra info - see #143

**Comment by bLeenstra** [comment] 2018-06-07 02:32
Closed as per previous comment

**Closed by bLeenstra** 2018-06-07 02:32 UTC
Labels: Bug, To Be Closed
